### ISSUE TITLE
Django version 1.9 above, we are getting this problem

### ISSUE THREAD

**Issue by johnolegario** [jschrewe/django-mongoadmin#40]
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/mongoadmin/__init__.py", line 1, in <module>
    from .options import *
  File "/usr/local/lib/python2.7/dist-packages/mongoadmin/options.py", line 6, in <module>
    from mongoadmin.contenttypes.models import ContentType
  File "/usr/local/lib/python2.7/dist-packages/mongoadmin/contenttypes/models.py", line 1, in <module>
    from .utils import has_rel_db, get_model_or_document
  File "/usr/local/lib/python2.7/dist-packages/mongoadmin/contenttypes/utils.py", line 5, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/contenttypes/models.py", line 138, in <module>
    class ContentType(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 105, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 237, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by Bellaby** [comment]
Having the exact same issue with Django 1.11.4
Installed versions:
Django (1.11.4)
django-mongodbforms (0.3.1)
mongoadmin (0.2)
mongoengine (0.13.0)

**Comment by sebitoelcheater** [comment]
+1 please help

**Comment by MiltosD** [comment]
+1

**Comment by v0y** [comment]
yo, try this fork: https://github.com/hywhut/django-mongoadmin
